language: node_js
sudo: false
node_js:
- node
addons:
  firefox: '49.0.2'
  apt:
    packages:
    - oracle-java8-installer
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"
before_script:
- npm install web-component-tester bower polylint
- bower install
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- JAVA_HOME=/usr/lib/jvm/java-8-oracle PATH=/usr/lib/jvm/java-8-oracle/bin:$PATH xvfb-run wct
